### ISSUE TITLE
Implement ActivityPub Statuses

### ISSUE THREAD

**Issue by catgirlsec** [nsuchy/TwitterPub#1]
I was able to get ActivityPub Profile Actors working without too much trouble although statuses look a bit more complicated. This issues it.

**A valid status from Mastodon.social:**
```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "ostatus": "http://ostatus.org#",
      "atomUri": "ostatus:atomUri",
      "inReplyToAtomUri": "ostatus:inReplyToAtomUri",
      "conversation": "ostatus:conversation",
      "sensitive": "as:sensitive",
      "toot": "http://joinmastodon.org/ns#",
      "votersCount": "toot:votersCount"
    }
  ],
  "id": "https://mastodon.social/users/Gargron/statuses/102739652870393458",
  "type": "Note",
  "summary": null,
  "inReplyTo": null,
  "published": "2019-09-05T11:24:51Z",
  "url": "https://mastodon.social/@Gargron/102739652870393458",
  "attributedTo": "https://mastodon.social/users/Gargron",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "cc": [
    "https://mastodon.social/users/Gargron/followers"
  ],
  "sensitive": false,
  "atomUri": "https://mastodon.social/users/Gargron/statuses/102739652870393458",
  "inReplyToAtomUri": null,
  "conversation": "tag:mastodon.social,2019-09-05:objectId=123026436:objectType=Conversation",
  "content": "\\u003cp\\u003eMy dream for Mastodon is for it to be a viable choice as a publishing platform for any creator. In other words, for people to not feel like they\\u0026apos;re locked in to Twitter or Instagram if they want to be professionally successful.\\u003c/p\\u003e",
  "contentMap": {
    "en": "\\u003cp\\u003eMy dream for Mastodon is for it to be a viable choice as a publishing platform for any creator. In other words, for people to not feel like they\\u0026apos;re locked in to Twitter or Instagram if they want to be professionally successful.\\u003c/p\\u003e"
  },
  "attachment": [],
  "tag": [],
  "replies": {
    "id": "https://mastodon.social/users/Gargron/statuses/102739652870393458/replies",
    "type": "Collection",
    "first": {
      "type": "CollectionPage",
      "next": "https://mastodon.social/users/Gargron/statuses/102739652870393458/replies?only_other_accounts=true\\u0026page=true",
      "partOf": "https://mastodon.social/users/Gargron/statuses/102739652870393458/replies",
      "items": []
    }
  }
}
```

**Current approach:**
```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams"
  ],
  "id": "http://localhost:4567/users/ulayer_net/statuses/1198833867089760257",
  "type": "Note",
  "summary": null,
  "inReplyTo": null,
  "published": "21:20 - 24. Nov. 2019",
  "url": "http://localhost:4567/ulayer_net/1198833867089760257",
  "attributedTo": "http://localhost:4567/users/ulayer_net",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "cc": [
    "http://localhost:4567/users/ulayer_net/followers"
  ],
  "sensitive": false,
  "content": "Our #Tor relays are looking good :)\n\n@torproject #InternetFreedom #Privacy #Security #AntiCensorshippic.twitter.com/OLWf1QEIdBShout out to @Snowden @JulianAssange_ @xychelsea @Thomas_Drake1 @DanielEllsberg @joshuawongcf @JesselynRadack we named our relays after you. Thank you for all your work!Thank you.",
  "attachment": [],
  "tag": []
}
```

**References:**
- https://www.w3.org/TR/activitypub/
- https://www.w3.org/ns/activitystreams

**Comment by catgirlsec** [comment]
I've learned that statuses are _probably_ valid but I need to implement an outbox. I'm working on it now.

**Comment by catgirlsec** [comment]
I get this error when attempting to implement the outbox code. I'm relatively certain the problem occurs at https://github.com/nsuchy/TwitterPub/blob/master/app.rb#L225 because I can visit http://localhost:8000/:user/status/:status_id and get_activity_status works without any issue (with the same status referened in the outbox draft code)
```
nathanielsuchy@Nathaniels-MacBook-Pro activitypub % ruby app.rb
/Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1641: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mustermann-1.1.0/lib/mustermann.rb:63: warning: The called method `new' is defined here
/Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1604: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1621: warning: The called method `compile!' is defined here
[2020-01-01 17:09:17] INFO  WEBrick 1.6.0
[2020-01-01 17:09:17] INFO  ruby 2.7.0 (2019-12-25) [x86_64-darwin19]
== Sinatra (v2.0.7) has taken the stage on 8000 for development with backup from WEBrick
[2020-01-01 17:09:17] INFO  WEBrick::HTTPServer#start: pid=77197 port=8000
https://twitter.com/glaad/status/outbox
[DEPRECATION] HTTParty will no longer override `response#nil?`. This functionality will be removed in future versions. Please, add explicit check `response.body.nil? || response.body.empty?`. For more info refer to: https://github.com/jnunemaker/httparty/issues/568
/Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/nokogiri-1.10.7/lib/nokogiri/html/document.rb:199:in `parse'
2020-01-01 17:09:23 - NoMethodError - undefined method `inner_text' for nil:NilClass:
        /Users/nathanielsuchy/Code/activitypub/utils/get_twitter_status.rb:27:in `get_twitter_status'
        /Users/nathanielsuchy/Code/activitypub/utils/get_activity_status.rb:3:in `get_activity_status'
        app.rb:158:in `block in <main>'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1635:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1635:in `block in compile!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1006:in `route_eval'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1035:in `block in process_route'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1033:in `catch'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1033:in `process_route'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:985:in `block in route!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:984:in `each'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:984:in `route!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1097:in `block in dispatch!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `block in invoke'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `catch'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `invoke'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1094:in `dispatch!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:919:in `block in call!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `block in invoke'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `catch'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `invoke'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:919:in `call!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:908:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.7/lib/rack/protection/xss_header.rb:18:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.7/lib/rack/protection/path_traversal.rb:16:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.7/lib/rack/protection/json_csrf.rb:26:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.7/lib/rack/protection/base.rb:50:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.7/lib/rack/protection/base.rb:50:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.7/lib/rack/protection/frame_options.rb:31:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.0.8/lib/rack/logger.rb:15:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.0.8/lib/rack/common_logger.rb:33:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:231:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:224:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.0.8/lib/rack/head.rb:12:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.0.8/lib/rack/method_override.rb:22:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/show_exceptions.rb:22:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:194:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1950:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1502:in `block in call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1729:in `synchronize'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1502:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.0.8/lib/rack/handler/webrick.rb:86:in `service'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
127.0.0.1 - - [01/Jan/2020:17:09:23 EST] "GET /glaad/outbox HTTP/1.1" 500 144098
- -> /glaad/outbox
https://twitter.com/__sinatra__/status/500.png
[DEPRECATION] HTTParty will no longer override `response#nil?`. This functionality will be removed in future versions. Please, add explicit check `response.body.nil? || response.body.empty?`. For more info refer to: https://github.com/jnunemaker/httparty/issues/568
/Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/nokogiri-1.10.7/lib/nokogiri/html/document.rb:199:in `parse'
2020-01-01 17:09:24 - NoMethodError - undefined method `inner_text' for nil:NilClass:
        /Users/nathanielsuchy/Code/activitypub/utils/get_twitter_status.rb:27:in `get_twitter_status'
        /Users/nathanielsuchy/Code/activitypub/utils/get_activity_status.rb:3:in `get_activity_status'
        app.rb:158:in `block in <main>'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1635:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1635:in `block in compile!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1006:in `route_eval'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1035:in `block in process_route'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1033:in `catch'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1033:in `process_route'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:985:in `block in route!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:984:in `each'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:984:in `route!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1097:in `block in dispatch!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `block in invoke'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `catch'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `invoke'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1094:in `dispatch!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:919:in `block in call!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `block in invoke'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `catch'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `invoke'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:919:in `call!'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:908:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.7/lib/rack/protection/xss_header.rb:18:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.7/lib/rack/protection/path_traversal.rb:16:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.7/lib/rack/protection/json_csrf.rb:26:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.7/lib/rack/protection/base.rb:50:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.7/lib/rack/protection/base.rb:50:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.7/lib/rack/protection/frame_options.rb:31:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.0.8/lib/rack/logger.rb:15:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.0.8/lib/rack/common_logger.rb:33:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:231:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:224:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.0.8/lib/rack/head.rb:12:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.0.8/lib/rack/method_override.rb:22:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/show_exceptions.rb:22:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:194:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1950:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1502:in `block in call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1729:in `synchronize'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1502:in `call'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.0.8/lib/rack/handler/webrick.rb:86:in `service'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
        /Users/nathanielsuchy/.rbenv/versions/2.7.0/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
127.0.0.1 - - [01/Jan/2020:17:09:24 EST] "GET /__sinatra__/500.png HTTP/1.1" 500 143776
http://localhost:8000/glaad/outbox -> /__sinatra__/500.png
```

**Comment by catgirlsec** [comment]
Turned out that routes was trying to find a user named outbox instead of pulling the outbox route. The solution here was to move outbox above. I did a major refactor that makes it easier to reorder routes. See https://stackoverflow.com/questions/59556652/why-is-a-string-literal-passed-to-a-method-changed-to-one-of-the-arguments for more details.

At this point I just need to implement SQLite caching for profiles and statuses then update get_activity_status and get_activity_profile to use it along with the outbox route and I'll be good to go and outboxes and viewing statuses will work.
